version: "3"
services:
  httpd:
    build: docker/httpd
    ports:
      - 2057:80
    volumes:
      - .:/var/www/html
    links:
      - pgsql
    environment:
      - XDEBUG_CONFIG='remote_host=192.168.0.52'
  pgsql:
    build: docker/pgsql
    environment:
      - DBNAME='db'
      - DBUSER='root:password'
    ports:
      - 3057:5432
