<?php

namespace AppBundle\Repository;

/**
 * BabysitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabysitterRepository extends \Doctrine\ORM\EntityRepository
{
}
