<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Member;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Member[]
     */
    public function findConfirm()
    {
        $query = $this->_em->createQuery('SELECT m FROM AppBundle:Member m WHERE m.confirmedAt IS NOT null ');
        return $query->getResult();
    }
}
