<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MemberGroup;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * MemberGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberGroupRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $year
     * @return mixed
     * @throws NoResultException
     */
    public function findByOld($year)
    {
        $query = $this->_em->createQuery('SELECT g FROM AppBundle:MemberGroup g 
        WHERE :year BETWEEN g.beginOldMember AND g.endOldMember');
        $query->setParameter('year', $year);
        $query->setMaxResults(1);
        try {
            return $query->getSingleResult();
        } catch (NonUniqueResultException $e) {
            throw new \LogicException();
        }
    }

    public function countFreePlace(MemberGroup $group)
    {
        $maxPlace=26; //fixme move to db
        $query = $this->_em->createQuery('SELECT count(m) as c FROM AppBundle:Member m 
        WHERE m.group=:group AND m.expectant=FALSE');
        $query->setParameter('group', $group);
        $query->setMaxResults(1);
        try {
            $data=$query->getSingleResult();
            return $maxPlace-$data['c'];
        } catch (NonUniqueResultException $e) {
            throw new \LogicException();
        } catch (NoResultException $e) {
            return $maxPlace;
        }
    }
}
