<?php

namespace AppBundle\Repository;

/**
 * TShirtSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TShirtSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
